services:
  trino:
    image: docker.io/trinodb/trino:478@sha256:177bda76e5e6caf235de4502e10020a029d06dd2625709fbf5adf264b6295a1d
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: "admin"
      AWS_SECRET_ACCESS_KEY: "miniopass"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - $PWD/config/trino/etc:/usr/lib/trino/etc:ro
      - $PWD/config/trino/catalog:/etc/trino/catalog:ro
    depends_on:
      - hive-metastore
      - minio
