services:
  trino:
    image: docker.io/trinodb/trino:476@sha256:00125e40d063bc4816d165482f6044872b18b56026fb959d3b28ce1f96ffbbee
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: "admin"
      AWS_SECRET_ACCESS_KEY: "miniopass"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - $PWD/config/trino/etc:/usr/lib/trino/etc:ro
      - $PWD/config/trino/catalog:/etc/trino/catalog:ro
    depends_on:
      - hive-metastore
      - minio
