services:
  warehousekeeper:
    image: ghcr.io/miracum/util-images/warehousekeeper:v0.1.13
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    restart: "no"
    environment:
      AWS_ALLOW_HTTP: "1"
      AWS_REGION: "eu-central-1"
      AWS_ENDPOINT_URL: "https://nbg1.your-objectstorage.com/"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?}
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        python3 /opt/warehousekeeper/warehousekeeper.py optimize --bucket-name=analytics-on-fhir --database-name-prefix=warehouse/default/ --use-delta-rs=false
        python3 /opt/warehousekeeper/warehousekeeper.py vacuum   --bucket-name=analytics-on-fhir --database-name-prefix=warehouse/default/ --use-delta-rs=false --retention-hours=0 --dry-run=false --enforce-retention-duration=false
    volumes:
      - $PWD/config/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
