services:
  prometheus:
    image: docker.io/prom/prometheus:v3.7.3@sha256:49214755b6153f90a597adcbff0252cc61069f8ab69ce8411285cd4a560e8038
    ports:
      - 127.0.0.1:9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - $PWD/config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus:rw
    depends_on:
      - cadvisor
    deploy:
      resources:
        limits:
          memory: 1g

  cadvisor:
    image: ghcr.io/google/cadvisor:v0.53.0@sha256:c3770bd6fc6c6a9cb2b47143e6b3cc3fdd9d20a8453dffbb7e09a145e7e0c4e4
    ports:
      - 127.0.0.1:8090:8080
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      resources:
        limits:
          memory: 1g

volumes:
  prometheus-data: {}
