name: benchmark

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

permissions: read-all

jobs:
  benchmark:
    runs-on: ubuntu-24.04
    env:
      SYNTHEA_POPULATION_SIZE: "100"
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: "3.38.0"

      - name: Run benchmark
        env:
          SPARK_DRIVER_MEMORY: "8g"
        run: |
          task run

      - name: Upload results
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        if: ${{ always()}}
        with:
          name: benchmark-results
          path: |
            src/results/
